"""about me field in teacher table

Revision ID: 1e5e23e8cbfc
Revises: 143989b39c2d
Create Date: 2021-12-28 04:34:36.300934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5e23e8cbfc'
down_revision = '143989b39c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_about_me', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('teacher_about_me')

    # ### end Alembic commands ###
