"""rename quiz option fields

Revision ID: 437a54c9b31a
Revises: 6e69e79b6d36
Create Date: 2021-12-16 11:03:38.631327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437a54c9b31a'
down_revision = '6e69e79b6d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.drop_column('quiz_3')
        batch_op.drop_column('quiz_2')
        batch_op.drop_column('quiz_4')
        batch_op.drop_column('quiz_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_1', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('quiz_4', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('quiz_2', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('quiz_3', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
