"""separate quiz

Revision ID: 4a4f49170ca5
Revises: 437a54c9b31a
Create Date: 2021-12-16 11:15:27.519040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4f49170ca5'
down_revision = '437a54c9b31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.drop_constraint('fk_web_dev_chapter1_quiz_client_id_client', type_='foreignkey')
        batch_op.drop_column('option_2')
        batch_op.drop_column('client_id')
        batch_op.drop_column('option_4')
        batch_op.drop_column('option_3')
        batch_op.drop_column('option_1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_1', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('option_3', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('option_4', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('option_2', sa.BOOLEAN(), nullable=True))
        batch_op.create_foreign_key('fk_web_dev_chapter1_quiz_client_id_client', 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###
