"""webdev chapter 1 quiz options

Revision ID: 62e81553e3f3
Revises: 179416df9154
Create Date: 2021-12-16 10:03:05.277340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e81553e3f3'
down_revision = '179416df9154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter1_quiz_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_1', sa.Boolean(), nullable=True),
    sa.Column('quiz_2', sa.Boolean(), nullable=True),
    sa.Column('quiz_3', sa.Boolean(), nullable=True),
    sa.Column('quiz_4', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_dev_chapter1_quiz_options')
    # ### end Alembic commands ###
