"""rename quiz option fields

Revision ID: 6e69e79b6d36
Revises: 973e5b15701b
Create Date: 2021-12-16 11:02:00.684140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e69e79b6d36'
down_revision = '973e5b15701b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_dev_chapter1_quiz', sa.Column('option_1', sa.Boolean(), nullable=True))
    op.add_column('web_dev_chapter1_quiz', sa.Column('option_2', sa.Boolean(), nullable=True))
    op.add_column('web_dev_chapter1_quiz', sa.Column('option_3', sa.Boolean(), nullable=True))
    op.add_column('web_dev_chapter1_quiz', sa.Column('option_4', sa.Boolean(), nullable=True))
    op.drop_column('web_dev_chapter1_quiz', 'quiz_3')
    op.drop_column('web_dev_chapter1_quiz', 'quiz_1')
    op.drop_column('web_dev_chapter1_quiz', 'quiz_2')
    op.drop_column('web_dev_chapter1_quiz', 'quiz_4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_dev_chapter1_quiz', sa.Column('quiz_4', sa.BOOLEAN(), nullable=True))
    op.add_column('web_dev_chapter1_quiz', sa.Column('quiz_2', sa.BOOLEAN(), nullable=True))
    op.add_column('web_dev_chapter1_quiz', sa.Column('quiz_1', sa.BOOLEAN(), nullable=True))
    op.add_column('web_dev_chapter1_quiz', sa.Column('quiz_3', sa.BOOLEAN(), nullable=True))
    op.drop_column('web_dev_chapter1_quiz', 'option_4')
    op.drop_column('web_dev_chapter1_quiz', 'option_3')
    op.drop_column('web_dev_chapter1_quiz', 'option_2')
    op.drop_column('web_dev_chapter1_quiz', 'option_1')
    # ### end Alembic commands ###
