"""flask student stories table

Revision ID: 7c1cd37b02e6
Revises: aa2aa87a965d
Create Date: 2021-12-27 13:50:18.012256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1cd37b02e6'
down_revision = 'aa2aa87a965d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flask student stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('student_image', sa.String(length=300), nullable=True),
    sa.Column('body', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('allowed_status', sa.Boolean(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_flask student stories_admin_id_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flask student stories'))
    )
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flask student stories_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_flask student stories_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flask student stories_username'))
        batch_op.drop_index(batch_op.f('ix_flask student stories_timestamp'))

    op.drop_table('flask student stories')
    # ### end Alembic commands ###
