"""combine chapter 1 quiz and options

Revision ID: 8175b3194b5a
Revises: 5247a8a21ccc
Create Date: 2021-12-16 10:30:02.003801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8175b3194b5a'
down_revision = '5247a8a21ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz_options', schema=None) as batch_op:
        batch_op.drop_index('ix_web_dev_chapter1_quiz_options_timestamp')

    op.drop_table('web_dev_chapter1_quiz_options')
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiz_1', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quiz_2', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quiz_3', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quiz_4', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quiz_4')
        batch_op.drop_column('quiz_3')
        batch_op.drop_column('quiz_2')
        batch_op.drop_column('quiz_1')
        batch_op.drop_column('client_id')

    op.create_table('web_dev_chapter1_quiz_options',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quiz_1', sa.BOOLEAN(), nullable=True),
    sa.Column('quiz_2', sa.BOOLEAN(), nullable=True),
    sa.Column('quiz_3', sa.BOOLEAN(), nullable=True),
    sa.Column('quiz_4', sa.BOOLEAN(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_dev_chapter1_quiz_options', schema=None) as batch_op:
        batch_op.create_index('ix_web_dev_chapter1_quiz_options_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
