"""rename webdev chapter 1 objectives table

Revision ID: 81ab10a3fb40
Revises: 06a081b894f0
Create Date: 2021-12-15 09:23:06.515327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ab10a3fb40'
down_revision = '06a081b894f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter1_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_1', sa.Boolean(), nullable=True),
    sa.Column('objective_2', sa.Boolean(), nullable=True),
    sa.Column('objective_3', sa.Boolean(), nullable=True),
    sa.Column('objective_4', sa.Boolean(), nullable=True),
    sa.Column('objective_5', sa.Boolean(), nullable=True),
    sa.Column('objective_6', sa.Boolean(), nullable=True),
    sa.Column('objective_7', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_dev_chapter1_objectives_timestamp'), 'web_dev_chapter1_objectives', ['timestamp'], unique=False)
    op.drop_index('ix_chapter1_objectives_timestamp', table_name='chapter1_objectives')
    op.drop_table('chapter1_objectives')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter1_objectives',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('objective_1', sa.BOOLEAN(), nullable=True),
    sa.Column('objective_2', sa.BOOLEAN(), nullable=True),
    sa.Column('objective_3', sa.BOOLEAN(), nullable=True),
    sa.Column('objective_4', sa.BOOLEAN(), nullable=True),
    sa.Column('objective_5', sa.BOOLEAN(), nullable=True),
    sa.Column('objective_6', sa.BOOLEAN(), nullable=True),
    sa.Column('objective_7', sa.BOOLEAN(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chapter1_objectives_timestamp', 'chapter1_objectives', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_web_dev_chapter1_objectives_timestamp'), table_name='web_dev_chapter1_objectives')
    op.drop_table('web_dev_chapter1_objectives')
    # ### end Alembic commands ###
