"""webdev chapter1 options

Revision ID: 87ba2d5d167d
Revises: 4a4f49170ca5
Create Date: 2021-12-16 11:16:49.618758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ba2d5d167d'
down_revision = '4a4f49170ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter1_quiz_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_1', sa.Boolean(), nullable=True),
    sa.Column('option_2', sa.Boolean(), nullable=True),
    sa.Column('option_3', sa.Boolean(), nullable=True),
    sa.Column('option_4', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_dev_chapter1_quiz_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_dev_chapter1_quiz_options_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter1_quiz_options_timestamp'))

    op.drop_table('web_dev_chapter1_quiz_options')
    # ### end Alembic commands ###
