"""Create client table

Revision ID: 90fef03916bf
Revises: 
Create Date: 2021-12-13 08:26:55.880743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fef03916bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_full_name', sa.String(length=64), nullable=True),
    sa.Column('parent_email', sa.String(length=120), nullable=True),
    sa.Column('parent_phone', sa.String(length=120), nullable=True),
    sa.Column('parent_occupation', sa.String(length=120), nullable=True),
    sa.Column('parent_residence', sa.String(length=120), nullable=True),
    sa.Column('parent_password_hash', sa.String(length=128), nullable=True),
    sa.Column('student_full_name', sa.String(length=64), nullable=True),
    sa.Column('student_email', sa.String(length=120), nullable=True),
    sa.Column('student_phone', sa.String(length=120), nullable=True),
    sa.Column('student_school', sa.String(length=120), nullable=True),
    sa.Column('student_age', sa.Integer(), nullable=True),
    sa.Column('student_password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_parent_email'), 'client', ['parent_email'], unique=False)
    op.create_index(op.f('ix_client_parent_full_name'), 'client', ['parent_full_name'], unique=False)
    op.create_index(op.f('ix_client_parent_occupation'), 'client', ['parent_occupation'], unique=False)
    op.create_index(op.f('ix_client_parent_phone'), 'client', ['parent_phone'], unique=False)
    op.create_index(op.f('ix_client_parent_residence'), 'client', ['parent_residence'], unique=False)
    op.create_index(op.f('ix_client_student_age'), 'client', ['student_age'], unique=False)
    op.create_index(op.f('ix_client_student_email'), 'client', ['student_email'], unique=False)
    op.create_index(op.f('ix_client_student_full_name'), 'client', ['student_full_name'], unique=False)
    op.create_index(op.f('ix_client_student_phone'), 'client', ['student_phone'], unique=False)
    op.create_index(op.f('ix_client_student_school'), 'client', ['student_school'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_student_school'), table_name='client')
    op.drop_index(op.f('ix_client_student_phone'), table_name='client')
    op.drop_index(op.f('ix_client_student_full_name'), table_name='client')
    op.drop_index(op.f('ix_client_student_email'), table_name='client')
    op.drop_index(op.f('ix_client_student_age'), table_name='client')
    op.drop_index(op.f('ix_client_parent_residence'), table_name='client')
    op.drop_index(op.f('ix_client_parent_phone'), table_name='client')
    op.drop_index(op.f('ix_client_parent_occupation'), table_name='client')
    op.drop_index(op.f('ix_client_parent_full_name'), table_name='client')
    op.drop_index(op.f('ix_client_parent_email'), table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###
