"""combine chapter 1 quiz and options

Revision ID: 973e5b15701b
Revises: 8175b3194b5a
Create Date: 2021-12-16 10:44:01.850271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973e5b15701b'
down_revision = '8175b3194b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiz_1', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quiz_2', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quiz_3', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quiz_4', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quiz_4')
        batch_op.drop_column('quiz_3')
        batch_op.drop_column('quiz_2')
        batch_op.drop_column('quiz_1')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
