"""followers

Revision ID: 9d083d71b2b9
Revises: d2eea53dbe7b
Create Date: 2021-12-21 21:25:07.329129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d083d71b2b9'
down_revision = 'd2eea53dbe7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['student.id'], name=op.f('fk_followers_followed_id_student')),
    sa.ForeignKeyConstraint(['follower_id'], ['student.id'], name=op.f('fk_followers_follower_id_student'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
