"""about me and last seen fields

Revision ID: 9ee2ec9d1569
Revises: 0082fef5c2e0
Create Date: 2021-12-14 05:15:30.431969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ee2ec9d1569'
down_revision = '0082fef5c2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('parent_about_me', sa.String(length=140), nullable=True))
    op.add_column('client', sa.Column('parent_last_seen', sa.DateTime(), nullable=True))
    op.add_column('client', sa.Column('student_about_me', sa.String(length=140), nullable=True))
    op.add_column('client', sa.Column('student_last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'student_last_seen')
    op.drop_column('client', 'student_about_me')
    op.drop_column('client', 'parent_last_seen')
    op.drop_column('client', 'parent_about_me')
    # ### end Alembic commands ###
