"""add client id field in quiz table

Revision ID: ad43072accc7
Revises: da18f58455f0
Create Date: 2021-12-16 11:22:56.518432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad43072accc7'
down_revision = 'da18f58455f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_web_dev_chapter1_quiz_client_id_client'), 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_web_dev_chapter1_quiz_client_id_client'), type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
