"""new student parent table

Revision ID: c7eb85f4a3db
Revises: ad43072accc7
Create Date: 2021-12-20 10:21:25.889186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7eb85f4a3db'
down_revision = 'ad43072accc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_full_name', sa.String(length=64), nullable=True),
    sa.Column('parent_email', sa.String(length=120), nullable=True),
    sa.Column('parent_phone', sa.String(length=120), nullable=True),
    sa.Column('parent_occupation', sa.String(length=120), nullable=True),
    sa.Column('parent_residence', sa.String(length=120), nullable=True),
    sa.Column('parent_password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent'))
    )
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_parent_email'), ['parent_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_parent_parent_full_name'), ['parent_full_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_parent_parent_occupation'), ['parent_occupation'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_parent_phone'), ['parent_phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_parent_parent_residence'), ['parent_residence'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_full_name', sa.String(length=64), nullable=True),
    sa.Column('student_email', sa.String(length=120), nullable=True),
    sa.Column('student_phone', sa.String(length=120), nullable=True),
    sa.Column('student_school', sa.String(length=120), nullable=True),
    sa.Column('student_age', sa.Integer(), nullable=True),
    sa.Column('student_course', sa.String(length=120), nullable=True),
    sa.Column('student_password_hash', sa.String(length=128), nullable=True),
    sa.Column('student_about_me', sa.String(length=140), nullable=True),
    sa.Column('student_last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student'))
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_student_age'), ['student_age'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_student_course'), ['student_course'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_student_email'), ['student_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_student_full_name'), ['student_full_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_student_phone'), ['student_phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_student_school'), ['student_school'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_student_school'))
        batch_op.drop_index(batch_op.f('ix_student_student_phone'))
        batch_op.drop_index(batch_op.f('ix_student_student_full_name'))
        batch_op.drop_index(batch_op.f('ix_student_student_email'))
        batch_op.drop_index(batch_op.f('ix_student_student_course'))
        batch_op.drop_index(batch_op.f('ix_student_student_age'))

    op.drop_table('student')
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_parent_residence'))
        batch_op.drop_index(batch_op.f('ix_parent_parent_phone'))
        batch_op.drop_index(batch_op.f('ix_parent_parent_occupation'))
        batch_op.drop_index(batch_op.f('ix_parent_parent_full_name'))
        batch_op.drop_index(batch_op.f('ix_parent_parent_email'))

    op.drop_table('parent')
    # ### end Alembic commands ###
