"""webdev chapter 1 quiz

Revision ID: ce38a67e37a8
Revises: 81ab10a3fb40
Create Date: 2021-12-16 09:40:42.629079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce38a67e37a8'
down_revision = '81ab10a3fb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter1_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('quiz_1', sa.Boolean(), nullable=True),
    sa.Column('quiz_2', sa.Boolean(), nullable=True),
    sa.Column('quiz_3', sa.Boolean(), nullable=True),
    sa.Column('quiz_4', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_dev_chapter1_quiz_title'), 'web_dev_chapter1_quiz', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_dev_chapter1_quiz_title'), table_name='web_dev_chapter1_quiz')
    op.drop_table('web_dev_chapter1_quiz')
    # ### end Alembic commands ###
