"""student parent webdev chapter tables

Revision ID: d09210d6aac8
Revises: 
Create Date: 2021-12-20 11:11:31.976007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09210d6aac8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_full_name', sa.String(length=64), nullable=True),
    sa.Column('parent_email', sa.String(length=120), nullable=True),
    sa.Column('parent_phone', sa.String(length=120), nullable=True),
    sa.Column('parent_occupation', sa.String(length=120), nullable=True),
    sa.Column('parent_residence', sa.String(length=120), nullable=True),
    sa.Column('parent_password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent'))
    )
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_parent_email'), ['parent_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_parent_parent_full_name'), ['parent_full_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_parent_parent_occupation'), ['parent_occupation'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_parent_phone'), ['parent_phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_parent_parent_residence'), ['parent_residence'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_full_name', sa.String(length=64), nullable=True),
    sa.Column('student_email', sa.String(length=120), nullable=True),
    sa.Column('student_phone', sa.String(length=120), nullable=True),
    sa.Column('student_school', sa.String(length=120), nullable=True),
    sa.Column('student_age', sa.Integer(), nullable=True),
    sa.Column('student_course', sa.String(length=120), nullable=True),
    sa.Column('student_password_hash', sa.String(length=128), nullable=True),
    sa.Column('student_about_me', sa.String(length=140), nullable=True),
    sa.Column('student_last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student'))
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_student_age'), ['student_age'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_student_course'), ['student_course'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_student_email'), ['student_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_student_full_name'), ['student_full_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_student_phone'), ['student_phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_student_school'), ['student_school'], unique=False)

    op.create_table('chapter1_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_chapter1_comment_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapter1_comment'))
    )
    with op.batch_alter_table('chapter1_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter1_comment_timestamp'), ['timestamp'], unique=False)

    op.create_table('community_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_community_comment_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_community_comment'))
    )
    with op.batch_alter_table('community_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_comment_timestamp'), ['timestamp'], unique=False)

    op.create_table('web_dev_chapter1_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_1', sa.Boolean(), nullable=True),
    sa.Column('objective_2', sa.Boolean(), nullable=True),
    sa.Column('objective_3', sa.Boolean(), nullable=True),
    sa.Column('objective_4', sa.Boolean(), nullable=True),
    sa.Column('objective_5', sa.Boolean(), nullable=True),
    sa.Column('objective_6', sa.Boolean(), nullable=True),
    sa.Column('objective_7', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_web_dev_chapter1_objectives_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_dev_chapter1_objectives'))
    )
    with op.batch_alter_table('web_dev_chapter1_objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_dev_chapter1_objectives_timestamp'), ['timestamp'], unique=False)

    op.create_table('web_dev_chapter1_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_web_dev_chapter1_quiz_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_dev_chapter1_quiz'))
    )
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_dev_chapter1_quiz_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_dev_chapter1_quiz_title'), ['title'], unique=False)

    op.create_table('web_dev_chapter1_quiz_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_1', sa.Boolean(), nullable=True),
    sa.Column('option_2', sa.Boolean(), nullable=True),
    sa.Column('option_3', sa.Boolean(), nullable=True),
    sa.Column('option_4', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_web_dev_chapter1_quiz_options_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_dev_chapter1_quiz_options'))
    )
    with op.batch_alter_table('web_dev_chapter1_quiz_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_dev_chapter1_quiz_options_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter1_quiz_options_timestamp'))

    op.drop_table('web_dev_chapter1_quiz_options')
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter1_quiz_title'))
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter1_quiz_timestamp'))

    op.drop_table('web_dev_chapter1_quiz')
    with op.batch_alter_table('web_dev_chapter1_objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter1_objectives_timestamp'))

    op.drop_table('web_dev_chapter1_objectives')
    with op.batch_alter_table('community_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_comment_timestamp'))

    op.drop_table('community_comment')
    with op.batch_alter_table('chapter1_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter1_comment_timestamp'))

    op.drop_table('chapter1_comment')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_student_school'))
        batch_op.drop_index(batch_op.f('ix_student_student_phone'))
        batch_op.drop_index(batch_op.f('ix_student_student_full_name'))
        batch_op.drop_index(batch_op.f('ix_student_student_email'))
        batch_op.drop_index(batch_op.f('ix_student_student_course'))
        batch_op.drop_index(batch_op.f('ix_student_student_age'))

    op.drop_table('student')
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_parent_residence'))
        batch_op.drop_index(batch_op.f('ix_parent_parent_phone'))
        batch_op.drop_index(batch_op.f('ix_parent_parent_occupation'))
        batch_op.drop_index(batch_op.f('ix_parent_parent_full_name'))
        batch_op.drop_index(batch_op.f('ix_parent_parent_email'))

    op.drop_table('parent')
    # ### end Alembic commands ###
