"""email not unique in flask stories table

Revision ID: d733ecc9e3f0
Revises: fb4cc441e8ec
Create Date: 2021-12-27 16:11:49.132178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd733ecc9e3f0'
down_revision = 'fb4cc441e8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_flask student stories_email', type_='unique')
        batch_op.create_index(batch_op.f('ix_flask student stories_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flask student stories_email'))
        batch_op.create_unique_constraint('uq_flask student stories_email', ['email'])

    # ### end Alembic commands ###
