"""make student personal details uniquer

Revision ID: dc6bffeaff66
Revises: 91d0390f067a
Create Date: 2021-12-15 08:00:35.516623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6bffeaff66'
down_revision = '91d0390f067a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_student_email', table_name='client')
    op.create_index(op.f('ix_client_student_email'), 'client', ['student_email'], unique=True)
    op.drop_index('ix_client_student_full_name', table_name='client')
    op.create_index(op.f('ix_client_student_full_name'), 'client', ['student_full_name'], unique=True)
    op.drop_index('ix_client_student_phone', table_name='client')
    op.create_index(op.f('ix_client_student_phone'), 'client', ['student_phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_student_phone'), table_name='client')
    op.create_index('ix_client_student_phone', 'client', ['student_phone'], unique=False)
    op.drop_index(op.f('ix_client_student_full_name'), table_name='client')
    op.create_index('ix_client_student_full_name', 'client', ['student_full_name'], unique=False)
    op.drop_index(op.f('ix_client_student_email'), table_name='client')
    op.create_index('ix_client_student_email', 'client', ['student_email'], unique=False)
    # ### end Alembic commands ###
