"""last seen field parent

Revision ID: e78339b2458b
Revises: f946f466b4e7
Create Date: 2021-12-26 23:22:39.244260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78339b2458b'
down_revision = 'f946f466b4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.drop_column('parent_last_seen')

    # ### end Alembic commands ###
