"""timestamp field webdev chapter 1 quiz options

Revision ID: edd748cfe499
Revises: 62e81553e3f3
Create Date: 2021-12-16 10:08:36.267561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edd748cfe499'
down_revision = '62e81553e3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_web_dev_chapter1_quiz_options_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_quiz_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter1_quiz_options_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
