"""email field flask stories table

Revision ID: fb4cc441e8ec
Revises: 7c1cd37b02e6
Create Date: 2021-12-27 15:10:27.614096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4cc441e8ec'
down_revision = '7c1cd37b02e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_flask student stories_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_flask student stories_email'), type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
