"""new fields in teacher model

Revision ID: 07460fda57b8
Revises: 07b96b686611
Create Date: 2021-04-26 05:55:01.983426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07460fda57b8'
down_revision = '07b96b686611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('about_me', sa.String(length=300), nullable=True))
    op.add_column('teacher', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'last_seen')
    op.drop_column('teacher', 'about_me')
    # ### end Alembic commands ###
