"""discard chapter 1 obj status table

Revision ID: 11e5e331e5e9
Revises: eefe380ec8e2
Create Date: 2022-02-01 14:20:50.697956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e5e331e5e9'
down_revision = 'eefe380ec8e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter objectives', schema=None) as batch_op:
        batch_op.drop_index('ix_chapter objectives_chapter')
        batch_op.drop_index('ix_chapter objectives_timestamp')

    op.drop_table('chapter objectives')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter objectives',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course', sa.VARCHAR(length=140), nullable=True),
    sa.Column('chapter', sa.VARCHAR(length=64), nullable=True),
    sa.Column('review_objectives_link', sa.VARCHAR(length=140), nullable=True),
    sa.Column('objective_1', sa.VARCHAR(length=140), nullable=True),
    sa.Column('objective_2', sa.VARCHAR(length=140), nullable=True),
    sa.Column('objective_3', sa.VARCHAR(length=140), nullable=True),
    sa.Column('objective_4', sa.VARCHAR(length=140), nullable=True),
    sa.Column('objective_5', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.Column('allowed_status', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter objectives', schema=None) as batch_op:
        batch_op.create_index('ix_chapter objectives_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_chapter objectives_chapter', ['chapter'], unique=False)

    # ### end Alembic commands ###
