"""body html field in web dev chapter 1 table

Revision ID: 13dc045a89af
Revises: 70665c45ba12
Create Date: 2022-01-20 17:05:11.520571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13dc045a89af'
down_revision = '70665c45ba12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter1_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter1_comment', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
