"""WebDevChapter3Quiz5Options table

Revision ID: 28892caf41af
Revises: ef522718a34b
Create Date: 2022-02-03 12:57:31.088438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28892caf41af'
down_revision = 'ef522718a34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter_3_quiz_5_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_web_dev_chapter_3_quiz_5_options_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_dev_chapter_3_quiz_5_options'))
    )
    with op.batch_alter_table('web_dev_chapter_3_quiz_5_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_dev_chapter_3_quiz_5_options_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter_3_quiz_5_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter_3_quiz_5_options_timestamp'))

    op.drop_table('web_dev_chapter_3_quiz_5_options')
    # ### end Alembic commands ###
