"""update columns in chapter 1 quiz 1 table

Revision ID: 29aa81426df9
Revises: cb9d3f9cc88c
Create Date: 2022-01-12 10:54:26.995491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29aa81426df9'
down_revision = 'cb9d3f9cc88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter_1_quiz_1_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.String(length=140), nullable=True))
        batch_op.drop_column('option_1')
        batch_op.drop_column('option_2')
        batch_op.drop_column('option_4')
        batch_op.drop_column('option_3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter_1_quiz_1_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_3', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('option_4', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('option_2', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('option_1', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
