"""delete review link field in ChapterQuiz table

Revision ID: 2ae902861d50
Revises: 11e5e331e5e9
Create Date: 2022-02-02 15:45:22.493893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae902861d50'
down_revision = '11e5e331e5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter quiz', schema=None) as batch_op:
        batch_op.drop_column('review_quiz_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_quiz_link', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
