"""general mutlichoice answer 3 table

Revision ID: 30f416c53c0c
Revises: c570cac0e225
Create Date: 2022-02-04 06:54:54.648759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f416c53c0c'
down_revision = 'c570cac0e225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_multiple_choices_answer_3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_general_multiple_choices_answer_3_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_general_multiple_choices_answer_3'))
    )
    with op.batch_alter_table('general_multiple_choices_answer_3', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_multiple_choices_answer_3_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_multiple_choices_answer_3', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_multiple_choices_answer_3_timestamp'))

    op.drop_table('general_multiple_choices_answer_3')
    # ### end Alembic commands ###
