"""general mutlichoice answer 5 table

Revision ID: 336114c05e27
Revises: acc5d02ac26b
Create Date: 2022-02-04 06:59:02.638117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336114c05e27'
down_revision = 'acc5d02ac26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_multiple_choices_answer_5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_general_multiple_choices_answer_5_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_general_multiple_choices_answer_5'))
    )
    with op.batch_alter_table('general_multiple_choices_answer_5', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_multiple_choices_answer_5_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_multiple_choices_answer_5', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_multiple_choices_answer_5_timestamp'))

    op.drop_table('general_multiple_choices_answer_5')
    # ### end Alembic commands ###
