"""WebDevChapter3Objectives table

Revision ID: 34ad24eabc6c
Revises: 8028c3e35dfb
Create Date: 2022-02-03 12:13:45.716348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ad24eabc6c'
down_revision = '8028c3e35dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter3_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_1', sa.Boolean(), nullable=True),
    sa.Column('objective_2', sa.Boolean(), nullable=True),
    sa.Column('objective_3', sa.Boolean(), nullable=True),
    sa.Column('objective_4', sa.Boolean(), nullable=True),
    sa.Column('objective_5', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_web_dev_chapter3_objectives_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_dev_chapter3_objectives'))
    )
    with op.batch_alter_table('web_dev_chapter3_objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_dev_chapter3_objectives_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter3_objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter3_objectives_timestamp'))

    op.drop_table('web_dev_chapter3_objectives')
    # ### end Alembic commands ###
