"""body html field in blog articles table

Revision ID: 369877048656
Revises: 13dc045a89af
Create Date: 2022-01-20 18:25:03.990437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369877048656'
down_revision = '13dc045a89af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    with op.batch_alter_table('blog_articles', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
