"""teacher table

Revision ID: 421ac8b216dc
Revises: b0619f03ee9e
Create Date: 2021-12-20 13:24:43.187695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421ac8b216dc'
down_revision = 'b0619f03ee9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_full_name', sa.String(length=64), nullable=True),
    sa.Column('teacher_email', sa.String(length=120), nullable=True),
    sa.Column('teacher_phone', sa.String(length=120), nullable=True),
    sa.Column('teacher_residence', sa.String(length=120), nullable=True),
    sa.Column('teacher_course', sa.String(length=120), nullable=True),
    sa.Column('teacher_password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher'))
    )
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_teacher_course'), ['teacher_course'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_teacher_email'), ['teacher_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_teacher_teacher_full_name'), ['teacher_full_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_teacher_teacher_phone'), ['teacher_phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_teacher_teacher_residence'), ['teacher_residence'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_teacher_residence'))
        batch_op.drop_index(batch_op.f('ix_teacher_teacher_phone'))
        batch_op.drop_index(batch_op.f('ix_teacher_teacher_full_name'))
        batch_op.drop_index(batch_op.f('ix_teacher_teacher_email'))
        batch_op.drop_index(batch_op.f('ix_teacher_teacher_course'))

    op.drop_table('teacher')
    # ### end Alembic commands ###
