"""web dev overview table

Revision ID: 439783bb7f69
Revises: aa5ba63f6c59
Create Date: 2021-12-28 17:00:08.040047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439783bb7f69'
down_revision = 'aa5ba63f6c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web development overview',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('overview', sa.String(length=140), nullable=True),
    sa.Column('youtube_link', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('allowed_status', sa.Boolean(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_web development overview_teacher_id_teacher')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web development overview'))
    )
    with op.batch_alter_table('web development overview', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web development overview_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_web development overview_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web development overview', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web development overview_title'))
        batch_op.drop_index(batch_op.f('ix_web development overview_timestamp'))

    op.drop_table('web development overview')
    # ### end Alembic commands ###
