"""rename field

Revision ID: 4a6bb5728405
Revises: 7903590ef087
Create Date: 2022-02-04 09:55:26.762117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6bb5728405'
down_revision = '7903590ef087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_quiz_1_link', sa.String(length=140), nullable=True))
        batch_op.drop_column('chapter_1_quiz_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_1_quiz_link', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('chapter_quiz_1_link')

    # ### end Alembic commands ###
