"""web dev chapter1 quiz total score

Revision ID: 4d127961cbf8
Revises: f6fa2f24b6a2
Create Date: 2022-03-02 11:46:32.912478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d127961cbf8'
down_revision = 'f6fa2f24b6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter1_quiz_total_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_web_dev_chapter1_quiz_total_score_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_dev_chapter1_quiz_total_score'))
    )
    with op.batch_alter_table('web_dev_chapter1_quiz_total_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_dev_chapter1_quiz_total_score_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_dev_chapter1_quiz_total_score_total_score'), ['total_score'], unique=False)

    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.drop_index('ix_web_dev_chapter1_quiz_timestamp')
        batch_op.drop_index('ix_web_dev_chapter1_quiz_title')

    op.drop_table('web_dev_chapter1_quiz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter1_quiz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_web_dev_chapter1_quiz_student_id_student'),
    sa.PrimaryKeyConstraint('id', name='pk_web_dev_chapter1_quiz')
    )
    with op.batch_alter_table('web_dev_chapter1_quiz', schema=None) as batch_op:
        batch_op.create_index('ix_web_dev_chapter1_quiz_title', ['title'], unique=False)
        batch_op.create_index('ix_web_dev_chapter1_quiz_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('web_dev_chapter1_quiz_total_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter1_quiz_total_score_total_score'))
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter1_quiz_total_score_timestamp'))

    op.drop_table('web_dev_chapter1_quiz_total_score')
    # ### end Alembic commands ###
