"""general mutlichoice answer 6 table

Revision ID: 4f50d56a2640
Revises: 336114c05e27
Create Date: 2022-02-04 07:00:04.254272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f50d56a2640'
down_revision = '336114c05e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_multiple_choices_answer_6',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_general_multiple_choices_answer_6_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_general_multiple_choices_answer_6'))
    )
    with op.batch_alter_table('general_multiple_choices_answer_6', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_multiple_choices_answer_6_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_multiple_choices_answer_6', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_multiple_choices_answer_6_timestamp'))

    op.drop_table('general_multiple_choices_answer_6')
    # ### end Alembic commands ###
