"""general multiple choices quiz table

Revision ID: 52cc0a6e6ac8
Revises: 28892caf41af
Create Date: 2022-02-04 04:49:07.233635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cc0a6e6ac8'
down_revision = '28892caf41af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general mulitple choices quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=140), nullable=True),
    sa.Column('chapter', sa.String(length=64), nullable=True),
    sa.Column('quiz_1', sa.String(length=140), nullable=True),
    sa.Column('quiz_2', sa.String(length=140), nullable=True),
    sa.Column('quiz_3', sa.String(length=140), nullable=True),
    sa.Column('quiz_4', sa.String(length=140), nullable=True),
    sa.Column('quiz_5', sa.String(length=140), nullable=True),
    sa.Column('quiz_6', sa.String(length=140), nullable=True),
    sa.Column('quiz_7', sa.String(length=140), nullable=True),
    sa.Column('quiz_8', sa.String(length=140), nullable=True),
    sa.Column('quiz_9', sa.String(length=140), nullable=True),
    sa.Column('quiz_10', sa.String(length=140), nullable=True),
    sa.Column('allowed_status', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_general mulitple choices quiz_teacher_id_teacher')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_general mulitple choices quiz'))
    )
    with op.batch_alter_table('general mulitple choices quiz', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general mulitple choices quiz_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_general mulitple choices quiz_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general mulitple choices quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general mulitple choices quiz_timestamp'))
        batch_op.drop_index(batch_op.f('ix_general mulitple choices quiz_chapter'))

    op.drop_table('general mulitple choices quiz')
    # ### end Alembic commands ###
