"""client table

Revision ID: 57901e6873f1
Revises: 
Create Date: 2021-05-13 17:38:10.824390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57901e6873f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_full_name', sa.String(length=64), nullable=False),
    sa.Column('parent_email', sa.String(length=120), nullable=False),
    sa.Column('verification_phone', sa.String(length=16), nullable=True),
    sa.Column('student_full_name', sa.String(length=64), nullable=False),
    sa.Column('student_email', sa.String(length=120), nullable=False),
    sa.Column('student_username', sa.String(length=64), nullable=False),
    sa.Column('student_course', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=300), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client'))
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_parent_email'), ['parent_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_parent_full_name'), ['parent_full_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_student_email'), ['student_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_student_full_name'), ['student_full_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_student_username'), ['student_username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_student_username'))
        batch_op.drop_index(batch_op.f('ix_client_student_full_name'))
        batch_op.drop_index(batch_op.f('ix_client_student_email'))
        batch_op.drop_index(batch_op.f('ix_client_parent_full_name'))
        batch_op.drop_index(batch_op.f('ix_client_parent_email'))

    op.drop_table('client')
    # ### end Alembic commands ###
