"""student private messages

Revision ID: 67e05ceddbf2
Revises: d150a26d70d7
Create Date: 2022-01-22 06:00:52.517680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e05ceddbf2'
down_revision = 'd150a26d70d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['student.id'], name=op.f('fk_student_message_recipient_id_student')),
    sa.ForeignKeyConstraint(['sender_id'], ['student.id'], name=op.f('fk_student_message_sender_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_message'))
    )
    with op.batch_alter_table('student_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_message_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('last_message_read_time')

    with op.batch_alter_table('student_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_message_timestamp'))

    op.drop_table('student_message')
    # ### end Alembic commands ###
