"""client comment table

Revision ID: 6b49ddfa5190
Revises: 57901e6873f1
Create Date: 2021-05-15 17:32:26.792054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b49ddfa5190'
down_revision = '57901e6873f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('fk_client_comment_client_id_client')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_comment'))
    )
    with op.batch_alter_table('client_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_comment_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_comment_timestamp'))

    op.drop_table('client_comment')
    # ### end Alembic commands ###
