"""teacher table

Revision ID: 6d3c4ed79494
Revises: 6b49ddfa5190
Create Date: 2021-05-16 07:47:08.193469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3c4ed79494'
down_revision = '6b49ddfa5190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_full_name', sa.String(length=64), nullable=False),
    sa.Column('teacher_email', sa.String(length=120), nullable=False),
    sa.Column('teacher_username', sa.String(length=64), nullable=False),
    sa.Column('verification_phone', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=300), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher'))
    )
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_teacher_email'), ['teacher_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_teacher_teacher_full_name'), ['teacher_full_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_teacher_teacher_username'), ['teacher_username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_teacher_username'))
        batch_op.drop_index(batch_op.f('ix_teacher_teacher_full_name'))
        batch_op.drop_index(batch_op.f('ix_teacher_teacher_email'))

    op.drop_table('teacher')
    # ### end Alembic commands ###
