"""body html field in flask anonymous template inheritance table

Revision ID: 70665c45ba12
Revises: 7b15b0456f39
Create Date: 2022-01-20 17:01:20.607253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70665c45ba12'
down_revision = '7b15b0456f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template inheritance comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template inheritance comment', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
