"""moderation link in chapters

Revision ID: 70ec687db254
Revises: f74013216713
Create Date: 2022-02-03 04:54:42.686066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ec687db254'
down_revision = 'f74013216713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_moderation_link', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('comment_moderation_link')

    # ### end Alembic commands ###
