"""body html field in flask student stories

Revision ID: 7b15b0456f39
Revises: 1627a77a0e55
Create Date: 2022-01-20 17:00:12.166386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b15b0456f39'
down_revision = '1627a77a0e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
