"""parent table

Revision ID: 7d4f0fa64901
Revises: 
Create Date: 2021-04-24 19:50:53.185479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d4f0fa64901'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('verification_phone', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_email'), 'parent', ['email'], unique=True)
    op.create_index(op.f('ix_parent_first_name'), 'parent', ['first_name'], unique=True)
    op.create_index(op.f('ix_parent_last_name'), 'parent', ['last_name'], unique=True)
    op.create_index(op.f('ix_parent_username'), 'parent', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_username'), table_name='parent')
    op.drop_index(op.f('ix_parent_last_name'), table_name='parent')
    op.drop_index(op.f('ix_parent_first_name'), table_name='parent')
    op.drop_index(op.f('ix_parent_email'), table_name='parent')
    op.drop_table('parent')
    # ### end Alembic commands ###
