"""WebDevChapter3Comment table

Revision ID: 8028c3e35dfb
Revises: a966ab72726d
Create Date: 2022-02-03 12:11:34.902514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8028c3e35dfb'
down_revision = 'a966ab72726d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter 3 comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('allowed_status', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_chapter 3 comment_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapter 3 comment'))
    )
    with op.batch_alter_table('chapter 3 comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter 3 comment_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter 3 comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter 3 comment_timestamp'))

    op.drop_table('chapter 3 comment')
    # ### end Alembic commands ###
