"""chapter link field in chapter table

Revision ID: 818468d23858
Revises: 1f24de1246ff
Create Date: 2021-12-29 13:27:11.245549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818468d23858'
down_revision = '1f24de1246ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_link', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('chapter_link')

    # ### end Alembic commands ###
