"""chapter table

Revision ID: 8951c53efcf4
Revises: 25438b5b4ec9
Create Date: 2021-12-28 22:13:58.572081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8951c53efcf4'
down_revision = '25438b5b4ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=140), nullable=True),
    sa.Column('chapter', sa.String(length=64), nullable=True),
    sa.Column('overview', sa.String(length=140), nullable=True),
    sa.Column('accomplish', sa.String(length=140), nullable=True),
    sa.Column('youtube_link', sa.String(length=140), nullable=True),
    sa.Column('conclusion', sa.String(length=140), nullable=True),
    sa.Column('objective_1', sa.String(length=140), nullable=True),
    sa.Column('objective_2', sa.String(length=140), nullable=True),
    sa.Column('objective_3', sa.String(length=140), nullable=True),
    sa.Column('objective_4', sa.String(length=140), nullable=True),
    sa.Column('objective_5', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('allowed_status', sa.Boolean(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_chapter_teacher_id_teacher')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapter'))
    )
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_timestamp'))
        batch_op.drop_index(batch_op.f('ix_chapter_chapter'))

    op.drop_table('chapter')
    # ### end Alembic commands ###
