"""flask student stories remove unique on email

Revision ID: 967bb0288edf
Revises: 00f001a958b1
Create Date: 2022-03-04 07:02:13.541906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967bb0288edf'
down_revision = '00f001a958b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_flask student stories_email', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_flask student stories_email', ['email'])

    # ### end Alembic commands ###
