"""new field in teacher community table table

Revision ID: 9ba65a6787c0
Revises: c61db0bcdbf4
Create Date: 2022-01-20 18:35:57.042453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba65a6787c0'
down_revision = 'c61db0bcdbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher community comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher community comment', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
