"""webdev chapter 2 quiz 5 table

Revision ID: a966ab72726d
Revises: ebb0fcc35ec9
Create Date: 2022-02-03 10:23:19.926174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a966ab72726d'
down_revision = 'ebb0fcc35ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter_2_quiz_5_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_web_dev_chapter_2_quiz_5_options_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_dev_chapter_2_quiz_5_options'))
    )
    with op.batch_alter_table('web_dev_chapter_2_quiz_5_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_dev_chapter_2_quiz_5_options_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter_2_quiz_5_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter_2_quiz_5_options_timestamp'))

    op.drop_table('web_dev_chapter_2_quiz_5_options')
    # ### end Alembic commands ###
