"""teacher private messages

Revision ID: aca16f68e9b9
Revises: 19e7a202e8e3
Create Date: 2022-01-21 05:28:58.979828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca16f68e9b9'
down_revision = '19e7a202e8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['teacher.id'], name=op.f('fk_teacher_message_recipient_id_teacher')),
    sa.ForeignKeyConstraint(['sender_id'], ['teacher.id'], name=op.f('fk_teacher_message_sender_id_teacher')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_message'))
    )
    with op.batch_alter_table('teacher_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_message_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_read_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('last_message_read_time')

    with op.batch_alter_table('teacher_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_message_timestamp'))

    op.drop_table('teacher_message')
    # ### end Alembic commands ###
