"""remove course field in table of contents

Revision ID: af8044f0e1ae
Revises: 49e19883fcda
Create Date: 2021-12-29 01:07:13.916026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8044f0e1ae'
down_revision = '49e19883fcda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table of contents', schema=None) as batch_op:
        batch_op.drop_column('course')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('table of contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
