"""admin table

Revision ID: b010cb32b9c1
Revises: 29e48091912e
Create Date: 2021-12-26 01:32:21.342629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b010cb32b9c1'
down_revision = '29e48091912e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_full_name', sa.String(length=64), nullable=True),
    sa.Column('admin_email', sa.String(length=64), nullable=True),
    sa.Column('admin_phone', sa.String(length=64), nullable=True),
    sa.Column('admin_last_seen', sa.DateTime(), nullable=True),
    sa.Column('admin_password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin'))
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_admin_email'), ['admin_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_admin_full_name'), ['admin_full_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_admin_phone'), ['admin_phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_admin_phone'))
        batch_op.drop_index(batch_op.f('ix_admin_admin_full_name'))
        batch_op.drop_index(batch_op.f('ix_admin_admin_email'))

    op.drop_table('admin')
    # ### end Alembic commands ###
