"""new fields in parent model

Revision ID: b63b46d48623
Revises: b53db8b2f9b9
Create Date: 2021-04-26 05:14:40.769477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63b46d48623'
down_revision = 'b53db8b2f9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('about_me', sa.String(length=300), nullable=True))
    op.add_column('parent', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'last_seen')
    op.drop_column('parent', 'about_me')
    # ### end Alembic commands ###
