"""teacher manages blog article table

Revision ID: b876334e8f6a
Revises: 7d5a5b61ce40
Create Date: 2022-01-17 16:01:12.481070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b876334e8f6a'
down_revision = '7d5a5b61ce40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_blog articles_teacher_id_teacher'), 'teacher', ['teacher_id'], ['id'])
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_blog articles_teacher_id_teacher'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'])
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
