"""general mutlichoice answer 9 table

Revision ID: bbc12bbd8a78
Revises: 05acfa92ecfa
Create Date: 2022-02-04 07:02:39.876328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc12bbd8a78'
down_revision = '05acfa92ecfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_multiple_choices_answer_9',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_general_multiple_choices_answer_9_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_general_multiple_choices_answer_9'))
    )
    with op.batch_alter_table('general_multiple_choices_answer_9', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_general_multiple_choices_answer_9_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_multiple_choices_answer_9', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_general_multiple_choices_answer_9_timestamp'))

    op.drop_table('general_multiple_choices_answer_9')
    # ### end Alembic commands ###
