"""review link field in chapter table

Revision ID: d152eb91621b
Revises: 818468d23858
Create Date: 2021-12-29 18:31:27.375427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd152eb91621b'
down_revision = '818468d23858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_review_link', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('chapter_review_link')

    # ### end Alembic commands ###
