"""chapter 1 quiz 1 options table

Revision ID: d269621317af
Revises: f1be4ab05a41
Create Date: 2022-01-12 10:11:00.325538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd269621317af'
down_revision = 'f1be4ab05a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter_1_quiz_1_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_1', sa.Boolean(), nullable=True),
    sa.Column('option_2', sa.Boolean(), nullable=True),
    sa.Column('option_3', sa.Boolean(), nullable=True),
    sa.Column('option_4', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_web_dev_chapter_1_quiz_1_options_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_dev_chapter_1_quiz_1_options'))
    )
    with op.batch_alter_table('web_dev_chapter_1_quiz_1_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_dev_chapter_1_quiz_1_options_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('web_dev_chapter1_quiz_options', schema=None) as batch_op:
        batch_op.drop_index('ix_web_dev_chapter1_quiz_options_timestamp')

    op.drop_table('web_dev_chapter1_quiz_options')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter1_quiz_options',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('option_1', sa.BOOLEAN(), nullable=True),
    sa.Column('option_2', sa.BOOLEAN(), nullable=True),
    sa.Column('option_3', sa.BOOLEAN(), nullable=True),
    sa.Column('option_4', sa.BOOLEAN(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_web_dev_chapter1_quiz_options_student_id_student'),
    sa.PrimaryKeyConstraint('id', name='pk_web_dev_chapter1_quiz_options')
    )
    with op.batch_alter_table('web_dev_chapter1_quiz_options', schema=None) as batch_op:
        batch_op.create_index('ix_web_dev_chapter1_quiz_options_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('web_dev_chapter_1_quiz_1_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter_1_quiz_1_options_timestamp'))

    op.drop_table('web_dev_chapter_1_quiz_1_options')
    # ### end Alembic commands ###
