"""remove unique constraint from parent table

Revision ID: d2eea53dbe7b
Revises: 421ac8b216dc
Create Date: 2021-12-20 22:14:45.240580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2eea53dbe7b'
down_revision = '421ac8b216dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.drop_index('ix_parent_parent_email')
        batch_op.create_index(batch_op.f('ix_parent_parent_email'), ['parent_email'], unique=False)
        batch_op.drop_index('ix_parent_parent_full_name')
        batch_op.create_index(batch_op.f('ix_parent_parent_full_name'), ['parent_full_name'], unique=False)
        batch_op.drop_index('ix_parent_parent_phone')
        batch_op.create_index(batch_op.f('ix_parent_parent_phone'), ['parent_phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_parent_phone'))
        batch_op.create_index('ix_parent_parent_phone', ['parent_phone'], unique=1)
        batch_op.drop_index(batch_op.f('ix_parent_parent_full_name'))
        batch_op.create_index('ix_parent_parent_full_name', ['parent_full_name'], unique=1)
        batch_op.drop_index(batch_op.f('ix_parent_parent_email'))
        batch_op.create_index('ix_parent_parent_email', ['parent_email'], unique=1)

    # ### end Alembic commands ###
