"""update columns in web dev chapter 1 quiz 3 table

Revision ID: d72ee76e6afa
Revises: 44a7ba6b3dbd
Create Date: 2022-01-12 11:12:56.059863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72ee76e6afa'
down_revision = '44a7ba6b3dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter_1_quiz_3_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.String(length=140), nullable=True))
        batch_op.drop_column('option_1')
        batch_op.drop_column('option_4')
        batch_op.drop_column('option_3')
        batch_op.drop_column('option_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter_1_quiz_3_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option_2', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('option_3', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('option_4', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('option_1', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
