"""web dev chapter 2 quiz table

Revision ID: d87c759cb70e
Revises: 70ec687db254
Create Date: 2022-02-03 05:42:24.955922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87c759cb70e'
down_revision = '70ec687db254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter2_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_web_dev_chapter2_quiz_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_dev_chapter2_quiz'))
    )
    with op.batch_alter_table('web_dev_chapter2_quiz', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_dev_chapter2_quiz_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_web_dev_chapter2_quiz_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter2_quiz', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter2_quiz_title'))
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter2_quiz_timestamp'))

    op.drop_table('web_dev_chapter2_quiz')
    # ### end Alembic commands ###
