"""blog articles table

Revision ID: e78122dde5e1
Revises: df1f352dd6c2
Create Date: 2021-12-27 06:52:45.257860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78122dde5e1'
down_revision = 'df1f352dd6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_name', sa.String(length=140), nullable=True),
    sa.Column('link', sa.String(length=140), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name=op.f('fk_blog articles_admin_id_admin')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog articles'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog articles')
    # ### end Alembic commands ###
