"""new fields in blog articles model

Revision ID: ee8f9a6b7d21
Revises: a1d82b689d6e
Create Date: 2021-12-27 11:42:07.064074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8f9a6b7d21'
down_revision = 'a1d82b689d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_image', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('body', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog articles', schema=None) as batch_op:
        batch_op.drop_column('body')
        batch_op.drop_column('article_image')

    # ### end Alembic commands ###
