"""student notifications

Revision ID: eefe380ec8e2
Revises: 67e05ceddbf2
Create Date: 2022-01-22 06:48:29.458293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefe380ec8e2'
down_revision = '67e05ceddbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_full_name', sa.String(length=128), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_student_notification_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_notification'))
    )
    with op.batch_alter_table('student_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_notification_student_full_name'), ['student_full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_notification_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_notification_timestamp'))
        batch_op.drop_index(batch_op.f('ix_student_notification_student_full_name'))

    op.drop_table('student_notification')
    # ### end Alembic commands ###
