"""flask student stories add unique on email

Revision ID: ef44d4529051
Revises: 967bb0288edf
Create Date: 2022-03-04 07:03:12.068896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef44d4529051'
down_revision = '967bb0288edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_flask student stories_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flask student stories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_flask student stories_email'), type_='unique')

    # ### end Alembic commands ###
