"""discard columns in web chapter 1 objectives

Revision ID: f1be4ab05a41
Revises: a4ac4ebb0084
Create Date: 2022-01-01 17:33:05.304824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1be4ab05a41'
down_revision = 'a4ac4ebb0084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_objectives', schema=None) as batch_op:
        batch_op.drop_column('objective_7')
        batch_op.drop_column('objective_6')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter1_objectives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective_6', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('objective_7', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
