"""chapter objectives table

Revision ID: f423ee23fdc0
Revises: d152eb91621b
Create Date: 2021-12-29 20:02:16.514571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f423ee23fdc0'
down_revision = 'd152eb91621b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=140), nullable=True),
    sa.Column('chapter', sa.String(length=64), nullable=True),
    sa.Column('review_objectives_link', sa.String(length=140), nullable=True),
    sa.Column('objective_1', sa.String(length=140), nullable=True),
    sa.Column('objective_2', sa.String(length=140), nullable=True),
    sa.Column('objective_3', sa.String(length=140), nullable=True),
    sa.Column('objective_4', sa.String(length=140), nullable=True),
    sa.Column('objective_5', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_chapter objectives_teacher_id_teacher')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapter objectives'))
    )
    with op.batch_alter_table('chapter objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter objectives_chapter'), ['chapter'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter objectives_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter objectives_timestamp'))
        batch_op.drop_index(batch_op.f('ix_chapter objectives_chapter'))

    op.drop_table('chapter objectives')
    # ### end Alembic commands ###
