"""webdev chapter 2 objectives table

Revision ID: f74013216713
Revises: 7101f488e0b5
Create Date: 2022-02-02 19:35:13.983482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74013216713'
down_revision = '7101f488e0b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_dev_chapter2_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objective_1', sa.Boolean(), nullable=True),
    sa.Column('objective_2', sa.Boolean(), nullable=True),
    sa.Column('objective_3', sa.Boolean(), nullable=True),
    sa.Column('objective_4', sa.Boolean(), nullable=True),
    sa.Column('objective_5', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_web_dev_chapter2_objectives_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_web_dev_chapter2_objectives'))
    )
    with op.batch_alter_table('web_dev_chapter2_objectives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_dev_chapter2_objectives_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_dev_chapter2_objectives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_dev_chapter2_objectives_timestamp'))

    op.drop_table('web_dev_chapter2_objectives')
    # ### end Alembic commands ###
