"""teacher comment table

Revision ID: 67434b219668
Revises: 6d3c4ed79494
Create Date: 2021-05-16 08:25:35.708490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67434b219668'
down_revision = '6d3c4ed79494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name=op.f('fk_teacher_comment_teacher_id_teacher')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_comment'))
    )
    with op.batch_alter_table('teacher_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_comment_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_comment_timestamp'))

    op.drop_table('teacher_comment')
    # ### end Alembic commands ###
