"""parent comment table

Revision ID: 01afa7565197
Revises: b7be488637c7
Create Date: 2021-05-05 13:17:19.072806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01afa7565197'
down_revision = 'b7be488637c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=300), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parent.id'], name=op.f('fk_parent_comment_parent_id_parent')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent_comment'))
    )
    with op.batch_alter_table('parent_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_comment_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_comment_timestamp'))

    op.drop_table('parent_comment')
    # ### end Alembic commands ###
