"""new fields in student model

Revision ID: 07b96b686611
Revises: b63b46d48623
Create Date: 2021-04-26 05:54:26.673602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b96b686611'
down_revision = 'b63b46d48623'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('about_me', sa.String(length=300), nullable=True))
    op.add_column('student', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'last_seen')
    op.drop_column('student', 'about_me')
    # ### end Alembic commands ###
